### ISSUE TITLE
Mining with CPU,/GPU is not possible anymore!!!

### ISSUE THREAD

**Issue by stoweo112** [kadena-io/chainweb-miner#30]
This month an Asicminer with powerfull 5.3Th/s hashing is also making FPGA Kadena Bistream obsolete very soon..
The start of a brand new mining generation for Kadena, Asic comes into Blake2S Network, 1first part brand name is IBLink Bm-K1 800 Watts Made by BROADENG of course Algo: Blake2S

**Comment by emilypi** [comment]
Hi @stoweo112 - I appreciate your frustration, but this is the wrong place to raise this kind of issue. Not only is it a *technical* (read: code) issues list for an older version of our GPU-based mining client, but this particular one has been deprecated for months. Per the README: 

> IMPORTANT NOTE: chainweb-miner is deprecated. Please use chainweb-mining-client instead.
